# Generated by Django 2.2.5 on 2019-11-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'SignUp',
            },
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='SignIn',
        ),
        migrations.AlterModelOptions(
            name='signin',
            options={'verbose_name_plural': 'SignIn'},
        ),
    ]
