# Generated by Django 2.2.5 on 2019-11-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191114_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Manager', 'Manager')], default='', max_length=6),
        ),
    ]
