# Generated by Django 2.2.5 on 2019-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191118_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
