# Generated by Django 2.2.5 on 2019-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Manager', 'Manager')], default='Manager', max_length=6),
        ),
    ]
