# Generated by Django 2.2.5 on 2019-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
