# Generated by Django 2.2.5 on 2019-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20191125_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
