# Generated by Django 2.2.5 on 2019-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20191125_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MaLE', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
